import type { Metadata } from "next";
import Link from "next/link";
import { BuildingIcon, MailIcon, MapIcon, PhoneIcon } from "@/components/icons";
import { PageHero } from "@/components/page-hero";
import { SectionHeading } from "@/components/section-heading";
import { municipality } from "@/data/municipality";
import { services } from "@/data/services";

export const metadata: Metadata = { title: "Local Government", description: "Current Ajuy officials, municipal contact information, public offices, and service guidance." };

export default function GovernmentPage() {
  return <><PageHero eyebrow="Local government" title="Leadership, offices, and public-service guidance" description="Find current published officials, municipal contact details, and a simple guide to the service area related to your concern."><BuildingIcon className="page-hero-icon" /></PageHero><section className="section"><div className="container"><SectionHeading eyebrow="Current published leadership" title="Municipal officials" description="The names below are listed in the current Iloilo Provincial Government municipal directory. Review them whenever local leadership changes." /><div className="official-grid"><article className="official-card"><span>Municipal Mayor</span><div className="official-avatar">LE</div><h2>{municipality.mayor}</h2><p>Leads the municipal executive branch and local administration.</p></article><article className="official-card"><span>Municipal Vice Mayor</span><div className="official-avatar">JR</div><h2>{municipality.viceMayor}</h2><p>Presides over the Sangguniang Bayan and supports municipal governance.</p></article><article className="official-contact"><span className="verified-label">Published directory details</span><h2>Ajuy Municipal Hall</h2><p>{municipality.address}</p><a href={`mailto:${municipality.email}`}><MailIcon />{municipality.email}</a>{municipality.phones.map((phone) => <a href={`tel:${phone.replace(/\s/g, "")}`} key={phone}><PhoneIcon />{phone}</a>)}<div className="button-row"><Link className="button" href="/contact">Contact the municipality</Link><a className="button button-outline" href="https://www.google.com/maps/search/?api=1&query=Ajuy+Municipal+Hall+Iloilo" target="_blank" rel="noreferrer"><MapIcon /> Map</a></div></article></div></div></section><section className="section section-soft"><div className="container"><SectionHeading eyebrow="Service guide" title="Choose the right starting point" description="These categories help visitors identify the likely municipal office. Exact requirements, fees, processing times, and schedules must still be confirmed directly." /><div className="service-grid">{services.map((service, index) => <article className="service-card" key={service.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{service.title}</h3><p>{service.description}</p></article>)}</div></div></section><section className="section"><div className="container alert-card"><div><p className="eyebrow">Official transactions</p><h2>Confirm requirements before paying or submitting documents.</h2><p>Use the published municipal phone numbers or email for current instructions. The website and AI assistant cannot approve applications, confirm payments, or issue official records.</p></div><div className="button-row"><Link className="button" href="/contact">Contact page</Link><Link className="button button-outline" href="/emergency">Emergency information</Link></div></div></section></>;
}
